config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'boards/index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  root 'home#index'

  get 'home/index'
  post 'home/trigger_refresh', as: 'trigger_refresh'
  post 'home/save_trello_token', as: 'save_trello_token'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :boards, only: %i[] do
    resources :lists, only: %i[index] do
      resources :cards, only: %i[index]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: boards
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  stats      :jsonb
#  user_id    :bigint(8)
#

class Board < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :lists
  has_many :cards, through: :lists

  def set_metrics!
    self.stats = { estimated: 0, actual: 0 }
    valid_lists = lists.reject { |list| list.stats.nil? }
    stats[:estimated] = valid_lists.map { |list| list.stats['estimated'].to_i }.sum
    stats[:actual] = valid_lists.map { |list| list.stats['actual'].to_i }.sum
    save!
  end
end

app/models/card.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cards
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  list_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  stats      :jsonb
#

class Card < ApplicationRecord
  belongs_to :list

  validates :name, presence: true

  after_create :set_metrics!

  private

  def set_metrics!
    self.stats = { estimated: 0, actual: 0 }
    estimated_hours = name.match(/\((\d*\.?\d+)\)/)
    actual_hours = name.match(/\[(\d*\.?\d+)\]/)
    stats[:estimated] = estimated_hours[1] if estimated_hours
    stats[:actual] = actual_hours[1] if actual_hours
    save!
    reload
    list.set_metrics!
  end
end

app/models/list.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: lists
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  board_id   :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  stats      :jsonb
#

class List < ApplicationRecord
  belongs_to :board
  has_many :cards

  validates :name, presence: true

  def set_metrics!
    self.stats = { estimated: 0, actual: 0 }
    valid_cards = cards.reject { |card| card.stats.nil? }
    stats[:estimated] = valid_cards.map { |card| card.stats['estimated'].to_i }.sum
    stats[:actual] = valid_cards.map { |card| card.stats['actual'].to_i }.sum
    save!
    reload
    board.set_metrics!
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  trello_token           :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boards
  has_many :lists, through: :boards
  has_many :cards, through: :lists

  enum tracking_status:
  {
    idle: 0,
    pulling: 1
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def index
    @list = List.find(params[:list_id]).decorate
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @user = current_user.decorate
  end

  def trigger_refresh
    if current_user.trello_token
      TrelloTrackingJob.perform_later(current_user.id)
      redirect_to root_path, notice: 'Refreshing!'
    else
      redirect_to root_path, alert: 'Cannot refresh without valid user token!'
    end
  end

  def save_trello_token
    current_user.update(trello_token: params[:trello_token])
    redirect_to root_path, notice: 'Trello Token Saved!'
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  def index
    @board = Board.find(params[:board_id]).decorate
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/cards/index.html.slim
.card-header.text-center
  h1 #{@list.name} Cards
.card-body
  .row.text-center
    .col-sm-6
      .card.card-default
        .card-header
          h2 General Stats
        .card-body
          b #{@list.card_count} Cards <br>
          span #{@list.estimated_hours_per_card} Estimated Hours Per Card <br>
          span #{@list.actual_hours_per_card} Actual Hours Per Card <br>
    .col-sm-6
      .card.card-default
        .card-header
          h2 Cards
        .card-body.text-left
          ol
            - @list.cards.each do |card|
              li
                span #{card.name}
                / = link_to card.name, board_list_card_path(board_id: @board.id, list_id: @list.id, card_id: card.id)
                br

app/views/home/index.html.slim
.card-header.text-center
  h1 Home
.card-body
  .row.text-center
    .col-sm-4
      .card.card-default
        .card-header
          h2 General Stats
        .card-body
          b #{@user.board_count} Boards <br>
          span #{@user.estimated_hours_per_board} Estimated Hours Per Board <br>
          span #{@user.actual_hours_per_board} Actual Hours Per Board <br> <br>
          b #{@user.list_count} Lists <br>
          span #{@user.estimated_hours_per_list} Estimated Hours Per List <br>
          span #{@user.actual_hours_per_list} Actual Hours Per List <br> <br>
          b #{@user.card_count} Cards <br>
          span #{@user.estimated_hours_per_card} Estimated Hours Per Card <br>
          span #{@user.actual_hours_per_card} Actual Hours Per Card <br>
          br
          hr
          b Progression Stats <br>
          span #{@user.cards_in_progress} Cards "In Progress" <br>
          span #{@user.cards_in_code_review} Cards In "Code Review" <br>
          span #{@user.cards_completed_this_sprint} Cards "Completed This Sprint"
    .col-sm-4
      .card.card-default
        .card-header
          h2 Alerts
        .card-body
          - if current_user.pulling?
            .card.card-default
              .card-header
                h4 System Pulling Data
              .card-body
                p You triggered a refresh of your account's Trello data to the Dev Dash. Please wait. Stats may be incorrect while this completes. You will need to manually refresh to watch this.
          - else
            .card.card-default
              .card-header
                h4 System Idle
              .card-body
                span The system is currently idle. If you would like to refresh the data in the system from your trello account, press the button below: <br>
                = link_to 'Trigger Refresh', trigger_refresh_path, method: :post, class: 'btn btn-default'

          - if @user.few_scrum_tracking_markers?
            br
            .card.card-default
              .card-header
                h4 Scrum For Trello
              .card-body
                p Most of your boards don't seem to have agile estimation and actual hour usage stats. Have you heard of the Scrum For Trello plugin for chrome?
                = link_to "Chrome Extension", 'https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje?hl=en'
          
          - if current_user.trello_token.nil?
            br
            .card.card-default
              .card-header
                h4 Missing Trello Token
              .card-body
                span Your user is currently missing it's Trello Token, which is necessary for the Dev Dash to fetch your data. Please input it below and save if you wish to use the Dev Dash.
                br
                span You can get this trello token from here: 
                = link_to 'Trello Token Page', "https://trello.com/1/authorize?expiration=never&scope=read,write,account&response_type=token&name=Server%20Token&key=#{ENV['TRELLO_API_KEY']}"
                = form_tag save_trello_token_path do |f|
                  = text_field_tag :trello_token
                  = submit_tag 'Save Token'  
    .col-sm-4
      .card.card-default
        .card-header
          h2 Your Boards
        .card-body.text-left
          ol
            - @user.boards.each do |board|
              li
                = link_to board.name, board_lists_path(board_id: board.id)
                br

app/views/layouts/_alerts.html.slim
- if !alert.nil?
  br
  .wrapper
    .container
      .col-lg-12
        .alert.alert-dismissible.alert-danger.text-center
          - if alert.is_a? String
            button type="button" class="close" data-dismiss="alert" &times;
            span.alert = alert
            br
          - else
            - alert.each do |alert|
              button type="button" class="close" data-dismiss="alert" &times;
              span.alert = alert
              br

- if !notice.nil?
  br
  .wrapper
    .container
      .col-lg-12
        .alert.alert-dismissible.alert-success.text-center
          button type="button" class="close" data-dismiss="alert" &times;
          p.notice = notice

app/views/layouts/_footer.html.slim
hr
.container-fluid.text-center
  span> © DevDash 2018. All Rights Reserved

app/views/layouts/application.html.slim
doctype html
html
  head
    title DevDash
    = csrf_meta_tags
    = csp_meta_tag

    / link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'  

    / script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
    script src="https://code.jquery.com/jquery-3.3.1.min.js"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"

  body.primary-bg
    = render 'layouts/navbar/navbar'
    = render 'layouts/alerts'
    .wrapper
      = yield
      = render 'layouts/footer'

app/views/layouts/navbar/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand[href="#"]
    | DevDash
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarColor01.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link[href= root_url]
          | Home 
          span.sr-only
            | (current)
      / - if current_user
        / = render 'layouts/navbar/colonies'
        / = render 'layouts/navbar/armies'
        / = render 'layouts/navbar/friends'

    - unless current_user.nil?
      ul.navbar-nav.navbar-right
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle[data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"]
            | #{current_user.email}
          .dropdown-menu
            = link_to 'Trigger Refresh', trigger_refresh_path, method: :post, class: 'dropdown-item'
            .dropdown-divider
            = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/lists/index.html.slim
.card-header.text-center
  h1 #{@board.name} Lists
.card-body
  .row.text-center
    .col-sm-6
      .card.card-default
        .card-header
          h2 General Stats
        .card-body
          b #{@board.list_count} Lists <br>
          span #{@board.estimated_hours_per_list} Estimated Hours Per List <br>
          span #{@board.actual_hours_per_list} Actual Hours Per List <br> <br>
          b #{@board.card_count} Cards <br>
          span #{@board.estimated_hours_per_card} Estimated Hours Per Card <br>
          span #{@board.estimated_hours_per_list} Actual Hours Per Card <br>
          br
          hr
          b Progression Stats <br>
          span #{@board.cards_in_progress} Cards "In Progress" <br>
          span #{@board.cards_in_code_review} Cards In "Code Review" <br>
          span #{@board.cards_completed_this_sprint} Cards "Completed This Sprint"
    .col-sm-6
      .card.card-default
        .card-header
          h2 Lists
        .card-body.text-left
          ol
            - @board.lists.each do |list|
              li
                = link_to list.name, board_list_cards_path(board_id: @board.id, list_id: list.id)
                br